name: Jonah Wiaderny
description: Random Logs
meta-description: Student of Economics at The University of Halle-Wittenberg. Includes CV, research, logs, and software.
url: http://www.wiaderny.org
domain: wiaderny.org
commentlinks: true
twitter-username: jonah.wiaderny
google-analytics-tracking-id: UA-16909425-8

source:      .
destination: ./_site
plugins:     ./_plugins

future:      true
lsi:         false
pygments:    true
markdown:    maruku
permalink:   /notes/:title/
paginate:    10

maruku:
  use_tex:    false
  use_divs:   false
  png_engine: blahtex
  png_dir:    images/latex
  png_url:    /images/latex

rdiscount:
  extensions: []

kramdown:
  auto_ids: true,
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

coderay:
    coderay_wrap: div
    coderay_line_numbers: inline
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: style