name: Jonah Wiaderny
description: MSc. in Banking and Financial Management, Managing Partner at Jonah Levi Diamanten
meta-description: MSc. in Banking and Financial Management, Managing Partner at Jonah Levi Diamanten. Includes CV and logs.
url: http://www.wiaderny.org
baseurl: http://www.wiaderny.org
commentlinks: true
twitter-username: jonahwiaderny
google-analytics-tracking-id: UA-16909425-8

source:      .
destination: ./_site
plugins_dir: ./_plugins

gems: [jekyll-paginate]

future:      true
lsi:         false
highlighter: 
markdown:    kramdown
permalink:   /notes/:title/
paginate:    10

maruku:
  use_tex:    false
  use_divs:   false
  png_engine: blahtex
  png_dir:    images/latex
  png_url:    /images/latex

rdiscount:
  extensions: []

kramdown:
  auto_ids: true,
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

coderay:
    coderay_wrap: div
    coderay_line_numbers: inline
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: style